# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-02 13:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='邮箱验证码', max_length=12)),
                ('email', models.CharField(help_text='邮箱', max_length=24)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='发送时间')),
            ],
            options={
                'verbose_name': '验证码',
            },
        ),
    ]
