# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-02 06:53
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiYu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='未命名', help_text='标题', max_length=12)),
                ('desc', models.CharField(help_text='时域内容', max_length=1024)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, help_text='创建时间')),
                ('keep_time', models.DateTimeField(help_text='到期日期')),
                ('is_open', models.IntegerField(default=0, help_text='是否打开，默认0不为打开，1为打开（可扩展）')),
                ('image', models.FileField(help_text='记忆照片', null=True, upload_to='upload/%Y/%m/%d')),
                ('open_code', models.CharField(default='', help_text='陌生人打开密码', max_length=10)),
                ('is_send', models.IntegerField(default=0, help_text='是否发送即将到期提醒邮件')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '时域库',
            },
        ),
    ]
